/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SystemImport } from './routes/system'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as ProfileIndexImport } from './routes/profile.index'
import { Route as VideoListImport } from './routes/video.list'
import { Route as ProfileCreateImport } from './routes/profile.create'
import { Route as VideoVideoIdIndexImport } from './routes/video.$videoId.index'
import { Route as VideoVideoIdPlayingImport } from './routes/video.$videoId.playing'

// Create/Update Routes

const SystemRoute = SystemImport.update({
  path: '/system',
  getParentRoute: () => rootRoute,
} as any)

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ProfileIndexRoute = ProfileIndexImport.update({
  path: '/profile/',
  getParentRoute: () => rootRoute,
} as any)

const VideoListRoute = VideoListImport.update({
  path: '/video/list',
  getParentRoute: () => rootRoute,
} as any)

const ProfileCreateRoute = ProfileCreateImport.update({
  path: '/profile/create',
  getParentRoute: () => rootRoute,
} as any)

const VideoVideoIdIndexRoute = VideoVideoIdIndexImport.update({
  path: '/video/$videoId/',
  getParentRoute: () => rootRoute,
} as any)

const VideoVideoIdPlayingRoute = VideoVideoIdPlayingImport.update({
  path: '/video/$videoId/playing',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemImport
      parentRoute: typeof rootRoute
    }
    '/profile/create': {
      id: '/profile/create'
      path: '/profile/create'
      fullPath: '/profile/create'
      preLoaderRoute: typeof ProfileCreateImport
      parentRoute: typeof rootRoute
    }
    '/video/list': {
      id: '/video/list'
      path: '/video/list'
      fullPath: '/video/list'
      preLoaderRoute: typeof VideoListImport
      parentRoute: typeof rootRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/video/$videoId/playing': {
      id: '/video/$videoId/playing'
      path: '/video/$videoId/playing'
      fullPath: '/video/$videoId/playing'
      preLoaderRoute: typeof VideoVideoIdPlayingImport
      parentRoute: typeof rootRoute
    }
    '/video/$videoId/': {
      id: '/video/$videoId/'
      path: '/video/$videoId'
      fullPath: '/video/$videoId'
      preLoaderRoute: typeof VideoVideoIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  LoginRoute,
  SignupRoute,
  SystemRoute,
  ProfileCreateRoute,
  VideoListRoute,
  ProfileIndexRoute,
  VideoVideoIdPlayingRoute,
  VideoVideoIdIndexRoute,
})

/* prettier-ignore-end */
