/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/videos/{videoId}/time": {
    post: operations["recordContentsTime"];
  };
  "/users/login": {
    post: operations["login"];
  };
  "/users/join": {
    post: operations["join"];
  };
  "/profiles": {
    post: operations["createProfile"];
  };
  "/profiles/{profileId}": {
    post: operations["chooseProfile"];
  };
  "/profiles/exit": {
    post: operations["exitProfile"];
  };
  "/file": {
    post: operations["uploadFile"];
  };
  "/videos": {
    get: operations["getContentsList"];
  };
  "/videos/{videoId}": {
    get: operations["contentInfo"];
  };
  "/users": {
    get: operations["queryUser"];
  };
  "/profiles/{profileId}/history": {
    get: operations["getProfileHistory"];
  };
  "/profiles/list": {
    get: operations["getProfileList"];
  };
  "/health": {
    get: operations["healthCheck"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    UsersAuth: {
      /** Format: int64 */
      userId?: number;
      /** Format: int64 */
      sessionId?: number;
    };
    TimeRecordRequest: {
      /** Format: float */
      time?: number;
    };
    LoginRequest: {
      loginId?: string;
      password?: string;
    };
    LoginResponse: {
      sessionId?: string;
    };
    JoinRequest: {
      loginId?: string;
      password?: string;
    };
    ProfileRequest: {
      nickname?: string;
      profileUri?: string;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      profilePassword?: string;
    };
    FileResponse: {
      url?: string;
    };
    Contents: {
      /** Format: int64 */
      id?: number;
      title?: string;
      description?: string;
      /** Format: float */
      duration?: number;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      thumbnailURI?: string;
      genre?: string;
      sourceURI?: string;
    };
    ContentsResponse: {
      contents?: components["schemas"]["Contents"][];
    };
    ContentInfo: {
      /** Format: int64 */
      id?: number;
      title?: string;
      description?: string;
      /** Format: float */
      duration?: number;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      thumbnailURI?: string;
      genre?: string;
      sourceURI?: string;
      /** Format: float */
      currentPlaybackTime?: number;
    };
    CurrentUserResponse: {
      loginId?: string;
      nickname?: string;
      profileURI?: string;
    };
    ProfileHistoryResponse: {
      videos?: components["schemas"]["Contents"][];
    };
    Profile: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      userId?: number;
      nickname?: string;
      imageURI?: string;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      password?: string;
    };
    ProfileResponse: {
      profiles?: components["schemas"]["Profile"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  recordContentsTime: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
      path: {
        videoId: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TimeRecordRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  join: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  createProfile: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": Record<string, never>;
        };
      };
    };
  };
  chooseProfile: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
      path: {
        profileId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  exitProfile: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  uploadFile: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** Format: binary */
          file: File;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["FileResponse"];
        };
      };
    };
  };
  getContentsList: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ContentsResponse"];
        };
      };
    };
  };
  contentInfo: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
      path: {
        videoId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ContentInfo"];
        };
      };
    };
  };
  queryUser: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CurrentUserResponse"];
        };
      };
    };
  };
  getProfileHistory: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
      path: {
        profileId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileHistoryResponse"];
        };
      };
    };
  };
  getProfileList: {
    parameters: {
      query: {
        user: components["schemas"]["UsersAuth"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileResponse"];
        };
      };
    };
  };
  healthCheck: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
}
