/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/profiles": {
    post: operations["createProfile"];
  };
  "/join": {
    post: operations["join"];
  };
  "/profiles/{profile_id}/history": {
    get: operations["getProfileHistory"];
  };
  "/profiles/list": {
    get: operations["getProfileList"];
  };
  "/health": {
    get: operations["healthCheck"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ProfileRequest: {
      nickname?: string;
      profileUri?: string;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      profilePassword?: string;
    };
    JoinRequest: {
      loginId?: string;
      password?: string;
    };
    Contents: {
      /** Format: int64 */
      id?: number;
      title?: string;
      description?: string;
      /** Format: float */
      duration?: number;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      thumbnailURI?: string;
      genre?: string;
      sourceURI?: string;
    };
    ProfileHistoryResponse: {
      videos?: components["schemas"]["Contents"][];
    };
    Profile: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      userId?: number;
      nickname?: string;
      imageURI?: string;
      /** @enum {string} */
      grade?: "CHILD" | "ADULT";
      password?: string;
    };
    ProfileResponse: {
      profiles?: components["schemas"]["Profile"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  createProfile: {
    parameters: {
      header: {
        sessionId: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProfileRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  join: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["JoinRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getProfileHistory: {
    parameters: {
      header: {
        sessionId: string;
      };
      path: {
        profile_id: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileHistoryResponse"];
        };
      };
    };
  };
  getProfileList: {
    parameters: {
      header: {
        sessionId: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProfileResponse"];
        };
      };
    };
  };
  healthCheck: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
}
